import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import CustomClerkProvider  from "@/services/clerk/components/component"; 
import { ThemeProvider } from "next-themes";

// outfit sans font
const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CustomClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${outfitSans.variable} ${outfitSans.variable} antialiased font-sans`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem enableColorScheme disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </CustomClerkProvider>
  );
}
